title: Le Zhang (张乐)
logo: /assets/img/me_2.PNG
description: Ph.D. Candidate, Department of Electrical and Electronic Engineering, University of Sheffield.

#Personal: [Google Scholar](https://scholar.google.com.hk/citations?user=eFrU7bMAAAAJ&hl=en)
#Email: le.zhang@sheffield.ac.uk or  andrew.senius@gmail.com

#** Due to graduate in August 2019, I will be open to a research position.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
